services:
  - type: web
    name: yurian-personal-website
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health.php
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yurian-personal-db
          property: connectionString

databases:
  - name: yurian-personal-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "18"
    databaseName: yurian_personal_db
    user: yurian_personal_db_user
