services:
  - type: web
    name: yurian-personal-website
    runtime: docker
    plan: free
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Africa/Dar_es_Salaam
      - key: DB_HOST
        fromDatabase:
          name: yurian-personal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: yurian-personal-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: yurian-personal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: yurian-personal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: yurian-personal-db
          property: password
databases:
  - name: yurian-personal-db
    plan: free
