services:
  - type: web
    name: yurian-personal-website
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Africa/Dar_es_Salaam
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: yurian-personal-db
          property: connectionString

databases:
  - name: yurian-personal-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "18"
    databaseName: yurian_personal_db
    user: yurian_personal_db_user
