<?php $displayProjects=$projects??projects(6);$displayProfile=$profile??profile();$domains=engineeringDomains();$notes=fieldNotes(); ?>
<main id="main-content" data-scroll-state="ORIGIN">
<section class="hq-hero" id="top"><div class="hq-hero__copy"><p class="eyebrow"><span class="signal-dot"></span> TANZANIA / EAT · <?=date('Y')?></p><h1>YURIAN<br><em>BUILDS</em><br>SYSTEMS.</h1><p class="hero-intro"><?=e($displayProfile['intro']??'I build software systems that turn complex problems into working products.')?></p><div class="hero-actions"><a class="hq-button hq-button--primary" href="/projects">View selected work <span>↘</span></a><a class="hq-text-link" href="/systems">Explore systems <span>↗</span></a></div></div><div class="universe-frame" aria-label="Yurian system signal"><div class="universe-meta"><span>PROJECT ZERO</span><span>ENGINEERING / PRODUCT / SYSTEMS</span></div><div class="signal-ring signal-ring--one"></div><div class="signal-ring signal-ring--two"></div><div class="signal-core"><span>Y</span></div><div class="signal-label">◉ IDENTITY / 001</div><div class="coordinates">SYSTEMS<br>PRODUCTS<br>SOFTWARE</div></div><div class="hero-foot"><span>© <?=date('Y')?> YURIAN</span><span>PROOF BEFORE PROMISES <i></i></span></div></section>
<section class="hq-section hq-identity" id="identity"><div class="section-label"><span>01</span><span>Position</span></div><div class="identity-grid"><p class="display-kicker">Software Engineer.<br><em>Product Builder.</em><br>Systems Architect.<br>Founder.</p><div class="identity-copy"><p class="lede">I build software systems that turn complex problems into working products. The portfolio prioritizes the work itself: architecture, implementation, decisions, repositories and verifiable project records.</p><div class="identity-details"><div><span>ROLE</span><p>Engineer / Builder<br>Independent operator</p></div><div><span>BASED IN</span><p><?=e($displayProfile['location']??'Tanzania')?><br>Working globally</p></div><div><span>PROOF MODEL</span><p><i class="status-pulse"></i> Evidence over claims</p></div></div></div></div></section>
<section class="hq-section hq-projects" id="projects"><div class="section-label"><span>02</span><span>Selected Work</span></div><div class="section-heading section-heading--projects"><h2>Built in the<br><em>real world.</em></h2><a class="hq-text-link" href="/projects">All work <span>↗</span></a></div><div class="project-stack"><?php foreach($displayProjects as $i=>$project): ?><article class="project-card"><div class="project-card__top"><span><?=chr(65+$i)?> / <?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><span><?=e($project['category']??'PROJECT')?></span></div><div class="project-card__main"><div class="project-glyph"><span><?=e(strtoupper(substr((string)($project['name']??'Y'),0,1)))?></span></div><div><h3><?=e($project['name']??'Project')?></h3><p><?=e($project['summary']??'')?></p></div><a href="/projects/<?=e($project['slug']??'project')?>" class="project-arrow" aria-label="Open dossier for <?=e($project['name']??'project')?>">↗</a></div><div class="project-card__foot"><span>PROJECT DOSSIER</span><a href="/projects/<?=e($project['slug']??'project')?>">Inspect evidence <span>›</span></a></div></article><?php endforeach; ?></div></section>
<section class="hq-section" id="systems"><div class="section-label"><span>03</span><span>Systems</span></div><div class="section-heading"><h2>Capability,<br><em>not badges.</em></h2><p>Engineering domains grouped by the problems the software has to solve.</p></div><div class="build-list"><?php foreach(array_slice($domains,0,6) as $i=>$domain): ?><a class="build-row" href="/systems"><span class="row-number"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><h3><?=e($domain['name'])?></h3><p><?=e($domain['summary'])?></p><span class="build-arrow">↗</span></a><?php endforeach; ?></div></section>
<section class="hq-section hq-current" id="now"><div class="section-label"><span>04</span><span>Now</span></div><div class="current-grid"><div><span class="status-chip"><i></i> PUBLISHED SNAPSHOT</span><h2>What is<br><em>being built.</em></h2><p>Current project records are shown with their stored status. No invented uptime, users, revenue or deployment telemetry.</p><a class="hq-button hq-button--outline" href="/now">Open Now ↗</a></div><div class="terminal-card"><div class="terminal-top"><span><i></i><i></i><i></i></span><span>yurian / project-zero</span><span>⌘</span></div><pre class="terminal-code"><span>01  evidence = project data</span>
<span>02  claims    = source required</span>
<span>03  motion    = purpose only</span>
<span>04  quality   = tested</span>
<span>05  output    = working software</span></pre></div></div></section>
<section class="hq-section" id="notes"><div class="section-label"><span>05</span><span>Engineering Notes</span></div><div class="notes-heading"><h2>How I<br><em>think.</em></h2><a class="hq-text-link" href="/blog">Read notes <span>↗</span></a></div><div class="notes-list"><?php foreach(array_slice($notes,0,3) as $note): ?><a class="note-row" href="/blog/<?=e($note['slug'])?>"><span><?=e($note['type'])?></span><div><small><?=e($note['date'])?></small><h3><?=e($note['title'])?></h3></div><span>↗</span></a><?php endforeach; ?></div></section>
<section class="hq-section" id="about"><div class="section-label"><span>06</span><span>Story</span></div><div class="identity-grid"><p class="display-kicker">The work is<br><em>the story.</em></p><div class="identity-copy"><p class="lede">Explore the actual projects, engineering records and notes rather than a résumé wrapped in animation.</p><a class="hq-button hq-button--outline" href="/about">Read about Yurian ↗</a></div></div></section>
<section class="hq-section" id="contact"><div class="section-label"><span>07</span><span>Contact</span></div><div class="cta-mark"><span>Y</span></div><h2>Build something<br><em>real.</em></h2><p>For a serious product, system or engineering problem, use the project intake.</p><a class="hq-button hq-button--primary" href="/contact">Start a conversation ↗</a></section>
</main>
<div class="command-palette" id="command-palette" hidden role="dialog" aria-modal="true" aria-labelledby="command-title"><div class="command-palette__panel"><div class="command-palette__head"><span id="command-title">YURIAN / NAVIGATION</span><button data-command-close aria-label="Close command palette">Esc</button></div><input id="command-input" type="search" placeholder="Search sections…" autocomplete="off"><div class="command-list"><button data-command-target="#projects">01 / Selected Work</button><button data-command-target="#systems">02 / Systems</button><button data-command-target="#now">03 / Now</button><button data-command-target="#notes">04 / Engineering Notes</button><button data-command-target="#about">05 / Story</button><button data-command-target="#contact">06 / Contact</button></div><p>Press <kbd>⌘</kbd><kbd>K</kbd> to open · <kbd>Esc</kbd> to close</p></div></div>