ServerName yurian-personal-website.onrender.com

<VirtualHost *:80>
    ServerName yurian-personal-website.onrender.com
    DocumentRoot /var/www/html/public
    Alias /admin /var/www/html/admin
    Alias /health.php /var/www/html/public/health.php

    <Directory /var/www/html/public>
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    <Directory /var/www/html/admin>
        AllowOverride All
        Require all granted
        DirectoryIndex index.php
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
