ALTER TABLE messages ADD COLUMN IF NOT EXISTS company VARCHAR(180);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS service VARCHAR(120);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS budget VARCHAR(80);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS timeline VARCHAR(80);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS stage VARCHAR(80);
CREATE INDEX IF NOT EXISTS idx_messages_status_created ON messages(status,created_at DESC);