<?php $canonicalUrl = url(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/'); ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="YURIAN — Independent software engineering, AI systems, digital products, and technology research.">
<meta name="theme-color" content="#0b1f3a">
<link rel="canonical" href="<?= e($canonicalUrl) ?>">
<meta property="og:type" content="website"><meta property="og:site_name" content="YURIAN"><meta property="og:title" content="<?= e($pageTitle ?? 'YURIAN — Technology & Digital Systems') ?>"><meta property="og:description" content="Independent software engineering, AI systems, digital products, and technology research."><meta property="og:url" content="<?= e($canonicalUrl) ?>"><meta property="og:image" content="<?= e(url('/assets/images/yurian-signal.jpg')) ?>"><meta property="og:image:alt" content="YURIAN technology and digital systems">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="<?= e($pageTitle ?? 'YURIAN — Technology & Digital Systems') ?>"><meta name="twitter:description" content="Independent software engineering, AI systems, digital products, and technology research."><meta name="twitter:image" content="<?= e(url('/assets/images/yurian-signal.jpg')) ?>">
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'Person','name'=>'Arshad Yurian Mwangi','alternateName'=>'Yurian','url'=>url('/'),'jobTitle'=>'Software Engineer, AI Builder, Technology Entrepreneur','description'=>'Independent software engineering, AI systems, digital products, and technology research.','sameAs'=>['https://github.com/yurian51']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script>
<title><?= e($pageTitle ?? 'YURIAN — Technology & Digital Systems') ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/forms.css"><link rel="stylesheet" href="/assets/css/light-theme.css"><link rel="stylesheet" href="/assets/css/institutional.css">
</head><body><a class="skip-link" href="#main-content">Skip to main content</a><div class="site-shell"><header class="navbar" id="site-nav"><a class="brand" href="/" aria-label="YURIAN home"><span class="brand-mark">Y</span><span>YURIAN <b>//</b> TECHNOLOGY</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation">Menu</button><nav id="primary-navigation" aria-label="Primary"><a href="/#identity">01 About</a><a href="/#build">02 Capabilities</a><a href="/projects">03 Portfolio</a><a href="/books">04 Publications</a><a href="/blog">05 Insights</a><a href="/contact">06 Contact</a></nav><a class="nav-menu" href="/cart" aria-label="Open publications cart">Cart</a></header>
