<?php $canonicalUrl=url(parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/'); ?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Yurian is a software engineer, product builder, systems architect and founder building software systems that turn complex problems into working products.">
<meta name="theme-color" content="#f5f1e8"><meta name="color-scheme" content="light dark"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/assets/icons/icon.svg" type="image/svg+xml"><link rel="canonical" href="<?=e($canonicalUrl)?>">
<meta property="og:type" content="website"><meta property="og:site_name" content="YURIAN"><meta property="og:title" content="<?=e($pageTitle??'YURIAN')?>"><meta property="og:description" content="Software engineer, product builder, systems architect and founder."><meta property="og:url" content="<?=e($canonicalUrl)?>"><meta property="og:image" content="<?=e(url('/assets/images/yurian-signal.jpg'))?>"><meta property="og:image:alt" content="Yurian personal website artwork">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="<?=e($pageTitle??'YURIAN')?>"><meta name="twitter:description" content="Software engineer, product builder, systems architect and founder."><meta name="twitter:image" content="<?=e(url('/assets/images/yurian-signal.jpg'))?>">
<script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Person','name'=>'Arshad Yurian Mwangi','alternateName'=>'Yurian','url'=>url('/'),'jobTitle'=>'Software Engineer, Product Builder, Systems Architect, Founder','description'=>'Building software systems that turn complex problems into working products.','sameAs'=>['https://github.com/yurian51'],'knowsAbout'=>['Software Engineering','Artificial Intelligence','Web Development','Digital Products','Systems Architecture']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<?php if(!empty($project)): ?><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'SoftwareSourceCode','name'=>$project['name']??'Project','description'=>$project['summary']??'','codeRepository'=>$project['repository_url']??null,'url'=>$project['live_url']??($project['url']??url('/projects/'.($project['slug']??''))),'programmingLanguage'=>$project['technologies']??[]],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_LINE_TERMINATORS)?></script><?php endif; ?>
<title><?=e($pageTitle??'YURIAN')?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/forms.css"><link rel="stylesheet" href="/assets/css/light-theme.css"><link rel="stylesheet" href="/assets/css/hybrid-hq.css"><link rel="stylesheet" href="/assets/css/realistic-editorial.css"><link rel="stylesheet" href="/assets/css/personal-platform.css"><link rel="stylesheet" href="/assets/css/world-class.css">
</head><body><div class="site-shell"><a class="skip-link" href="#main-content">Skip to content</a><header class="navbar" id="site-nav"><a class="brand" href="/" aria-label="YURIAN home"><span class="brand-mark" aria-hidden="true">Y</span><span>YURIAN <b>//</b> DIGITAL HQ</span></a><nav aria-label="Primary"><a href="/projects">Work</a><a href="/systems">Systems</a><a href="/about">About</a><a href="/now">Now</a><a href="/blog">Notes</a><a href="/under-the-hood">Under the hood</a><a href="/contact">Contact</a></nav><button class="nav-menu" type="button" data-command-open aria-label="Open command navigation">⌘K</button></header><script src="/assets/js/hq.js" defer></script><script src="/assets/js/hybrid-hq.js" defer></script><script src="/assets/js/pwa.js" defer></script><script src="/assets/js/personal-platform.js" defer></script><script src="/assets/js/world-class.js" defer></script>